### ISSUE TITLE
Mapeos Ciclistas

### ISSUE THREAD

**Issue by basicavisual** [CodeandoGuadalajara/empieza-aqui#1]
Hacer un evento dirigido a los colectivos ciclistas de ZMG donde les demos herramientas de mapeo participativo:
- Ciclovías
- Bicis blancas

De aquí podría derivarse un proyecto para los periodistas que incluya una nota sobre el mapeo de bicis blancas.
#### Antecedentes:

https://www.facebook.com/events/809879722478796/
http://repubikla.org/
https://repubikla.cartodb.com/maps

**Comment by thehackermonkey** [comment]
Podríamos hablar con la banda de Núcleo (que traen un grupo ciclista importante) y convocar junto con ellos  para dar una charla sobre el proyecto y un taller para usar  http://mapme.com

**Comment by thehackermonkey** [comment]
Cerrado, ahora existe el repo [Mapeo Ciclista](https://github.com/CodeandoGuadalajara/mapeociclista)
